title: <p align="center"> Swarnendu Sarkar </p>
logo: /assets/img/Id_Pic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/swarnendu-sarkar-05b61750/">LinkedIn</a> |
  <a href="https://github.com/sarkarswarnendu7">GitHub</a>
  
  <br>   
  I have a working experience of various Machine learning, Time series forecasting problems.
  I have worked on Predictive Modeliing, Fraud detection, Pricing optimization as well.
  <br>
  </p>



theme: jekyll-theme-minimal
